import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import AppProvider from "./components/AppProvider";
import { Toaster } from "sonner";
import SearchInput from "./components/post/SearchInput";
import { POST } from "./constants/post.constant";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body>
        <AppProvider>
          <div className="max-w-3/4 mx-auto py-5">
            <h1 className="text-3xl text-center font-semibold">{POST.title}</h1>
            <SearchInput />
            {children}
          </div>
        </AppProvider>
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
